---
- name: Get Helm install script
  get_url:
    url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    dest: /tmp/get-helm-3.sh
    mode: 0700

- name: Install Helm
  command: /tmp/get-helm-3.sh
  args:
    creates: /usr/local/bin/helm
  register: helm_install
