---
- name: Update all apt packages
  hosts: all
  become: true
  tasks:
    - name: Update apt packages
      ansible.builtin.apt:
        name: "*"
        state: latest
        update_cache: yes
    - name: Install Rsync
      ansible.builtin.apt:
        name: rsync
        state: present

- name: Install Node Exporter
  hosts: all
  become: true
  vars:
    node_exporter_version: 1.8.2
  roles:
    - role: prometheus.prometheus.node_exporter