---
- name: Setup Elasticsearch Cluster
  import_tasks: setup-k3s.yaml

- name: Create Benchmark Directory
  file:
    path: "/var/benchmarks/elastic_default_{{ run_num }}"
    state: directory

- name: Setup metadata for ingestion benchmark
  include_tasks: setup-ingest-meta.yaml

- name: Create Benchmark Index
  uri:
    url: "http://{{ elastic_host }}:{{elastic_port}}/{{elastic_index}}"
    method: PUT
    status_code: 200
    return_content: true
    url_password: "{{ elastic_password }}"
    url_username: "elastic"
    body_format: json
    headers:
      Content-Type: "application/json"
    body: "{\"settings\" : { \"number_of_replicas\" : 2}}"