---
openobserve_host: "openobserve.benchmark.local"
openobserve_port: 80
kubeconfig_path: "/etc/rancher/k3s/k3s.yaml"
openobserve_username: "benchmark@benchmark.local"
openobserve_password: "benchmark@benchmark.local"
openobserve_stream: "benchmark"
openobserve_org: "default"
max_start: 0
max_end: 0
run_num: 0
flog_sleep_in_us: 1
# 1 hour in nanoseconds
query_range: 30000000000